### PR TITLE
Removed variable assignment, where the variable is unused

### PR DESCRIPTION
**Pull request by olimortimer**

### CODE REVIEW

**Comment by gocart** [comment]
This one exposed a problem in one of the files. In particular it's the AdminCoupons.php file.
$promo_id should not be $promo_id it should be just $id, and it's used on line 150.

I'll take a look at the others too to make sure we're not dealing with something similar.

**Comment by gocart** [comment]
I found some other ones like this as well. It looks like these removals may have been the result of an automated search or something along those lines. I'll go ahead and do the fixes that I found and perhaps we can revisit the other removals afterward.

**Comment by olimortimer** [comment]
Ah, good spot. Yes, I used phpmd to find unused code (something I run on most of my projects), but double checked everything before I removed the offending variables etc - however, I didn't spot the ones where the variables were named incorrectly!

**Comment by gocart** [comment]
I went ahead and fixed many, if not all of these manually in the repository and updated the few I found that were erroneously modified in the original commit. One required a different variable name and several others should have had the whole line (not just the variable) removed all together. Thanks!

**Comment by olimortimer** [comment]
Cheers @gocart (Noah)

**Pull request closed without merging**
